---
apiVersion: v1
kind: Service
metadata:
  name: django-auth
  labels:
    app: django-auth
spec:
  selector:
    app: django-auth
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 8001
      name: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-auth-deployment
  labels:
    app: django-auth
spec:
  replicas: 2
  selector:
    matchLabels:
      app: django-auth
  template:
    metadata:
      labels:
        app: django-auth
    spec:
      containers:
      - name: django-auth
        image: django-auth:1.0
        ports:
        - containerPort: 8001
        env:
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: auth-secrets
              key: POSTGRES_DB
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: auth-secrets
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: auth-secrets
              key: POSTGRES_PASSWORD
        - name: POSTGRES_HOST
          valueFrom:
            secretKeyRef:
              name: auth-secrets
              key: POSTGRES_HOST
        - name: POSTGRES_PORT
          valueFrom:
            secretKeyRef:
              name: auth-secrets
              key: POSTGRES_PORT
        - name: FORTYTWO_UID
          valueFrom:
            secretKeyRef:
              name: auth-secrets
              key: FORTYTWO_UID
        - name: FORTYTWO_SECRET
          valueFrom:
            secretKeyRef:
              name: auth-secrets
              key: FORTYTWO_SECRET
        